joyjoin/service/joyjoin/all/urls.py
from django.urls import path

from . import views
from sec.views import preferences

app_name = 'all'

urlpatterns = [
    path('', views.all, name='all'),
    path('404devel', views.error_404, name='404devel'),
    path('preferences', preferences, name='preferences'),
]

joyjoin/service/joyjoin/create/urls.py
from django.urls import path

from . import views

app_name = 'create'

urlpatterns = [
    path('', views.create, name='create'),
    path('add/', views.add, name='add'),
]

joyjoin/service/joyjoin/joyjoin/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from all import views as all_views
import all

urlpatterns = [
    path('', all.views.about, name='about'),
    path('admin/', admin.site.urls),
    path('register/', include('register.urls')),
    path('login/', include('login.urls')),
    path('create/', include('create.urls')),
    path('user/', include('user.urls')),
    path('sec/', include('sec.urls')),
    path('all/', include('all.urls')),
    path('settings/', include('settings.urls')),
    path('post/', include('post.urls')),
    path('report/', include('report.urls')),
    path('rules/', all.views.regulamin, name='rules'),
]
handler404 = all_views.error_404
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

joyjoin/service/joyjoin/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [

    path('<int:post_id>/', views.post, name='post'),
    path('reply/', views.reply, name="reply"),
    path('change_sorting/', views.change_sorting, name="change_sorting"),
    path('vote_comment/<int:option>/', views.vote_comment, name='vote_comment'),
    path('vote/<int:option>/', views.vote, name='vote'),
    path('display_new_posts/', views.display_new_posts, name='display_new_posts'),
]

joyjoin/service/joyjoin/sec/urls.py
from django.urls import path

from . import views

app_name = 'sec'

urlpatterns = [
    path('<str:section_name>/', views.section, name='section'),
    path('<str:section_name>/tags/', views.tags, name='tags'),
    path('join/<str:section_name>/', views.join, name='join'),
    path('leave/<str:section_name>/', views.leave, name='leave'),
    path('<str:section_name>/preferences/',
         views.preferences, name='preferences'),
    path('<str:section_name>/update_punctation/',
         views.update_punctation, name='update_punctation'),
]

joyjoin/service/joyjoin/user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('<str:username>/', views.user, name='user'),
]

joyjoin/service/joyjoin/sec/views.py
from django.shortcuts import get_object_or_404, redirect, render

from common.activity import update_activity
from common.context import set_common_context
from common.models import User, Post, Section, Tag, TagPunctation, Vote
from post.views import get_posts
from sec.comments import get_comments_list


def section(request, section_name):
    """ Jest to funkcja, która przedstawia stronę zawierającą sekcje.

    Sprawdza czy użytkownik jest w danej sekcji i czy może napisać w niej post.

    Args:
        request(WSGIRequest):obiekt klasy WSGIRequest
        section_name(str):nazwa sekcji, dla której chcemy pobrać posty

    Returns:
        django.http.HtttpResponse:obiekt reprezentujący wyrenderowany widok 'sec/sec.html' z ustawionym kontekstem szablonu
    """
    try:
        tag_name = request.GET['tag']
    except KeyError:
        tag_name = None

    context = {}
    set_common_context(request, context)
    update_activity(context['current_user'])
    context['current_section_name'] = request.session['current_section_name'] = section_name

    posts_to_display = []

    if section_name != 'all':
        current_section = get_object_or_404(Section, name=section_name)
        context['current_section'] = current_section
        context['this_is_the_all_view'] = False

        if context['current_user']:
            if current_section.users.filter(login=context['current_user'].login):
                context['current_user_in_current_section'] = True
            else:
                context['current_user_in_current_section'] = False
        else:
            context['current_user_in_current_section'] = False

        participants = list(current_section.users.all())
        participants.sort(key=lambda x: len(Post.objects.filter(author=x, section=current_section)), reverse=True)
    else:
        context['this_is_the_all_view'] = True
        posts_to_display = Post.objects.order_by('-creation_time')

        participants = list(User.objects.all())
        participants.sort(key=lambda x: len(Post.objects.filter(author=x)), reverse=True)

    selected_posts = posts_to_display
    posts_to_display = []

    for post in selected_posts:
        is_liked = False
        is_disliked = False
        if Vote.objects.filter(post=post, user=context['current_user'], reaction=1).exists():
            is_liked = True
        if Vote.objects.filter(post=post, user=context['current_user'], reaction=-1).exists():
            is_disliked = True

        comments_to_display = get_comments_list(post, context['current_user'])
        posts_to_display.append((post, post.count_votes(
            1), post.count_votes(-1), is_liked, is_disliked, comments_to_display))

    context['posts_to_display'] = posts_to_display
    context['this_is_section_view'] = True
    context['section_name'] = section_name
    context['tag_name'] = tag_name
    request.session['list_of_displayed_posts'] = []
    posts_to_display = get_posts(request,
                                 section_name, tag_name)

    context['participants'] = participants[0:5]

    if tag_name is not None and len(posts_to_display) == 0:
        return redirect("sec:section", section_name)
    else:
        context['posts_to_display'] = posts_to_display

    return render(request, 'sec/sec.html', context)


def tags(request, section_name):
    """ Jest to funkcja, która przedstawia stronę zawierającą tagi

    Args:
        request(WSGIRequest):obiekt klasy WSGIRequest
        section_name(str):nazwa sekcji, dla której chcemy pobrać posty

    Returns:
        django.http.HtttpResponse:obiekt reprezentujący wyrenderowany widok 'sec/tags.html' z ustawionym kontekstem szablonu
    """
    current_section = get_object_or_404(Section, name=section_name)
    request.session['current_section_name'] = section_name

    context = {}
    set_common_context(request, context)
    update_activity(context['current_user'])

    # dołącz popularność do tagów
    tags_to_display = []
    posts_in_this_section = Post.objects.filter(section=current_section)
    for tag in Tag.objects.filter(section=current_section):
        popularity = 0
        for post in posts_in_this_section:
            if tag in post.tags.all() or tag in post.implied_tags.all():
                popularity += 1
        tags_to_display.append(('a', tag, popularity))
    usertags = {}
    for post in posts_in_this_section:
        for usertag in post.user_tags_as_list():
            try:
                usertags[usertag] += 1
            except KeyError:
                usertags[usertag] = 1
    for usertag in usertags:
        tags_to_display.append(('u', usertag, usertags[usertag]))

    # posortuj tagi wg popularności
    tags_to_display.sort(key=lambda x: -x[2])

    # odetnij tagi których nie chcemy wyświetlać (popularność == 0 albo dalej niż 20. miejsce)
    tags_to_display = [x for x in tags_to_display if x[2] > 0]
    # poniższy kod jest zakomentowany,
    # ponieważ nie jest póki co potrzebny
    # if len(tags_to_display) > 20:
    #     tags_to_display = tags_to_display[0:20]

    context['tags_to_display'] = tags_to_display
    return render(request, 'sec/tags.html', context)


def join_or_leave(request, section_name, action):
    """ Funkcja obsługująca żądanie dołączenia do lub opuszczenia sekcji

    Note:
        W zależności od argumentu ``action`` wywołuje jedną z funkcji:
            - join
            - leave

    Args:
        request(WSGIRequest): obiekt klasy WSGIRequest
        section_name(str): nazwa sekcji, dla której chcemy pobrać posty
        action(str): akcja, patrz notka wyżej

    Returns:
        django.http.HtttpResponse: zwraca przekierowanie do adresu 'sec/sec.html'
        section_name(str): nazwa sekcji, do której użytkownik chce dołączyć lub którą chce opuścić
    """
    context = {}
    set_common_context(request, context)
    update_activity(context['current_user'])
    current_user = context['current_user']
    if section_name != 'all':
        current_section = Section.objects.filter(name=section_name).first()
        if action == 'join':
            current_section.users.add(current_user)
        elif action == 'leave':
            current_section.users.remove(current_user)
    return redirect('sec:section', section_name)


def join(request, section_name):
    """ Funkcja obsługująca żądanie dołączenia do sekcji

    Args:
        request(WSGIRequest):obiekt klasy WSGIRequest
        section_name(str):nazwa sekcji, dla której chcemy pobrać posty

    Returns:
        django.http.HtttpResponse:obiekt reprezentujący wyrenderowany widok z funkcji join_or_leave po wybraniu akcji 'join'
        section_name(str):nazwa sekcji, dla której chcemy pobrać posty
    """
    return join_or_leave(request, section_name, 'join')


def leave(request, section_name):
    """ Funkcja obsługjąca żądanie opuszczenia sekcji

    Args:
        request(WSGIRequest):obiekt klasy WSGIRequest
        section_name(str):nazwa sekcji, dla której chcemy pobrać posty

    Returns:
        django.http.HtttpResponse:obiekt reprezentujący wyrenderowany widok z funkcji join_or_leave po wybraniu akcji 'leave'
        section_name(str):nazwa sekcji, dla której chcemy pobrać posty
    """
    return join_or_leave(request, section_name, 'leave')


def preferences(request, section_name='all'):
    """
    Funkcja, która renderuję podstronę preferences/

    Na tej stronie użytkownik może ustawić preferencje dla wybranych tagów.

    Args:
        request:WSGIRequest - obiekt klasy WSGIRequest
        section_name:str - nazwa sekcji dla której wyświetlamy punktacje tagów lub napis 'all' gdy chcemy wyswietlic wszystkie tagi w serwisie

    Returns:
        wyrenderowany kod html dla podstrony preferences.html

    Raises:
        Http404: gdy podano błędną nazwę sekcji lub użytkownik nie jest zalogowany
    """
    # Ustawia podstawowe atrybuty contextu i aktualizuje czas ostatniej aktywności użytkownika
    request.session['current_section_name'] = section_name
    context = {}
    set_common_context(request, context)
    update_activity(context['current_user'])

    # Tworzy pomocnicze obiekty
    current_user = get_object_or_404(
        User, login=request.session.get('logged_in_as', default=None))
    tags_to_display = {}
    if section_name == 'all':
        for section in Section.objects.all():
            tags_to_display[section.description] = []
    else:
        current_section = get_object_or_404(Section, name=section_name)
        tags_to_display[current_section.description] = []

    # Pobiera odpowiednie rekordy z bazy TagPunctation
    tps = TagPunctation.objects.filter(user=current_user)
    for tp in tps:
        if tp.tag.section.description in tags_to_display.keys():
            tp.punctation = int(tp.punctation/10)
            tags_to_display[tp.tag.section.description].append(tp)
    context['tags_to_display'] = tags_to_display
    # Jeżeli użytkownik zezwala na zmianę swoich punktacji to zaznacz checkboxa na podstronie
    if current_user.is_punctation_changeable is True:
        context['is_punctation_changeable'] = 'checked'
    else:
        context['is_punctation_changeable'] = ''

    # Pobiera datę ostatniej aktualizacji preferencji użytkownika
    context['last_update_punctation_time'] = current_user.last_update_punctation_time

    # Renderuje podstronę
    return render(request, 'sec/preferences.html', context)


def update_punctation(request, section_name):
    """
    Funkcja, która zapisuje ustawione punktacje użytkownika w bazie danych w tabeli TagPunctation

    Args:
        request:WSGIRequest - obiekt klasy WSGIRequest, pola tego obiektu wykorzystywane w tej funkcji:
            -) .session['logged_is_as']:str - login zalogowanego użytkownika
        section_name:str - nazwa sekcji dla której modyfikujemy punktację tagów

    Returns:
        wyrenderowany kod html dla podstrony preferences.html

    Raises:

joyjoin/service/joyjoin/sec/templates/sec/preferences.html
{% extends 'common/frame.html' %}
{% load static %}

	{% block sscss %}
	<link href='{% static 'sec/styles/preferences.css' %}' rel='stylesheet' type='text/css'>
	{% endblock %}
	
		{% block ssc %}
		<div id='content'>
			<h1>Preferencje</h1> <br>

			<form action="{% url 'sec:update_punctation' current_section_name %}" method="post">
			{% csrf_token %}
            {% for section_name, tps in tags_to_display.items %}
                <h2>{{section_name}}</h2>
                {% for tp in tps %}
                    <div class="tag_punctation_row">
                        <span class="tag_name">{{tp.tag.name}}</span>
                        <span>
                            <input type="range" id="range_{{tp.tag.id}}" name="{{tp.tag.id}}" min="-10" max="10" step="1" value="{{tp.punctation}}" oninput="changeCounter('{{tp.tag.id}}')">
                            <span id="counter_{{tp.tag.id}}" class="counter">{{tp.punctation}}</span>
                        </span> 
                        <button onclick="resetCounter('{{tp.tag.id}}', {{tp.punctation}})" class='reset_button'>Reset</button>
                    </div>
                {% endfor %}
            {% endfor %}
            <label><input type="checkbox" name="is_punctation_changeable" {{is_punctation_changeable}}> Pozwalaj algorytmowi na automatyczne modyfikowanie tych wartości </label> <br>
        
            <input type="submit" value="Zapisz">
            </form> <br>
			Ostatnia modyfikacja: {{last_update_punctation_time}}
		</div>
		{% endblock %}

joyjoin/service/joyjoin/sec/templates/sec/sec.html
{% extends 'common/frame.html' %}
{% load static %}


	{% block sscss %}
    <link href="{% static 'sec/styles/sec.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'post/post.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'post/simple_comment.css' %}" rel="stylesheet" type="text/css">
	{% endblock %}

	{% block hero-image %}
	<div id="hero-image"{% if not this_is_the_all_view %} class="sec" style="background-image: url('/static/common/img/{{section_name}}.jpg');" {% endif%}>
        <div>
            {% if this_is_the_all_view %}
            <img src="{% static 'common/img/logo/jj1000x300_shadow.png' %}" alt="logo">
            <h1>Dołącz do zabawy!</h1>
            {% else %}
            <h1><i class="icon-{{current_section.icon}}"></i>{{current_section.description}}</h1>
            {% endif %}
        </div>
    </div>
	{% endblock %}

	{% block ssc %}
	<div id="content">

		{% for post,liked,disliked,is_liked,is_disliked,comments in posts_to_display %}
		{% include 'post/single_post.html' %}
		{% endfor %}
	</div>
	{% endblock %}

	{% block available-options %}
        {% if not this_is_the_all_view %}
        <li><a href="{% url 'sec:tags' section_name %}">Tagi</a></li>
        {% endif %}
		{% if current_user  %}
			<li> <a href="{% url 'create:create' %}">Napisz post</a> </li>

			{% if not this_is_the_all_view %}
				{% if not current_user_in_current_section %}
				<li><a href="{% url 'sec:join' section_name %}">Dołącz do tej sekcji</a></li>
				{% else %}
					<li><a href="{% url 'sec:leave' section_name %}">Opuść tą sekcję</a></li>
				{% endif %}
                <li> <a href="{% url 'sec:preferences' section_name %}">Algorytm sortowania</a> </li>
			{% else %}
                <li> <a href="{% url 'all:preferences' %}">Algorytm sortowania</a> </li>
            {% endif %}
		{% endif %}
    {% endblock %}

    {% block right-menu %}
	<ul>
		<li>Najbardziej aktywni użytkownicy</li>
		{% for user in participants %}
        <li><a href="{% url 'user:user' user.login %}"><img class="avatar" alt="awatar użytkownika" src="{{user.image_mini.url}}"><span>{{user.name}}</span></a></li>
        {% endfor %}
	</ul>
	{% endblock %}
    
    {% block ssjs %}
        <script src="{% static 'sec/scripts/scripts.js' %}" type="text/javascript"></script>
    {% endblock %}
    
    {% block forms %}
    <div id="up">
        <i class="icon-up"></i>
    </div>
    
	<form id="display_new_posts" action="{% url 'post:display_new_posts' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="section_name" value="{{section_name}}">
        {% if tag_name %}
        <input type="hidden" name="tag_name" value="{{tag_name}}">
        {% endif %}
    </form>
	{% endblock %}

joyjoin/service/joyjoin/sec/templates/sec/tags.html
{% extends 'common/frame.html' %}
{% load static %}

	{% block sscss %}
	<link href='{% static 'sec/styles/tags.css' %}' rel='stylesheet' type='text/css'>
	{% endblock %}
	
		{% block ssc %}
		<div id='content'>
            <h1>Lista tagów</h1>
			<ul id="tag_list">
			{% for type, tag, pop in tags_to_display %}
			{% if type == 'a' %}{# tag zatwierdzony #}
				<li><a
						class='tag'
						href="{% url 'sec:section' current_section_name %}?tag={{ tag.slug_or_name }}"
						title="{{ tag.tooltip }}"
					>{{ tag.name }}</a> ({{ pop }})</li>
			{% elif type == 'u' %}{# tag wolny #}
				<li><a class='usertag' href="{% url 'sec:section' current_section_name %}?tag={{ tag }}">{{ tag }}</a> ({{ pop }})</li>
			{% endif %}
			{% endfor %}
			{% for tmp in usertags %}
				<li>{{ tmp }}</li>
			{% endfor %}
			</ul>
		</div>
		{% endblock %}