joyjoin/service/joyjoin/all/urls.py
from django.urls import path

from . import views
from sec.views import preferences

app_name = 'all'

urlpatterns = [
    path('', views.all, name='all'),
    path('404devel', views.error_404, name='404devel'),
    path('preferences', preferences, name='preferences'),
]

joyjoin/service/joyjoin/joyjoin/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from all import views as all_views
import all

urlpatterns = [
    path('', all.views.about, name='about'),
    path('admin/', admin.site.urls),
    path('register/', include('register.urls')),
    path('login/', include('login.urls')),
    path('create/', include('create.urls')),
    path('user/', include('user.urls')),
    path('sec/', include('sec.urls')),
    path('all/', include('all.urls')),
    path('settings/', include('settings.urls')),
    path('post/', include('post.urls')),
    path('report/', include('report.urls')),
    path('rules/', all.views.regulamin, name='rules'),
]
handler404 = all_views.error_404
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

joyjoin/service/joyjoin/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [

    path('<int:post_id>/', views.post, name='post'),
    path('reply/', views.reply, name="reply"),
    path('change_sorting/', views.change_sorting, name="change_sorting"),
    path('vote_comment/<int:option>/', views.vote_comment, name='vote_comment'),
    path('vote/<int:option>/', views.vote, name='vote'),
    path('display_new_posts/', views.display_new_posts, name='display_new_posts'),
]

joyjoin/service/joyjoin/sec/urls.py
from django.urls import path

from . import views

app_name = 'sec'

urlpatterns = [
    path('<str:section_name>/', views.section, name='section'),
    path('<str:section_name>/tags/', views.tags, name='tags'),
    path('join/<str:section_name>/', views.join, name='join'),
    path('leave/<str:section_name>/', views.leave, name='leave'),
    path('<str:section_name>/preferences/',
         views.preferences, name='preferences'),
    path('<str:section_name>/update_punctation/',
         views.update_punctation, name='update_punctation'),
]

joyjoin/service/joyjoin/user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('<str:username>/', views.user, name='user'),
]

joyjoin/service/joyjoin/post/views.py
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404

from common.context import set_common_context
from common.activity import update_activity
from common.models import Post, Vote, User, Comment, CommentVote
from common.models import comment_max_depth
from common.comment_sorting import comment_sorting_keys, sort_comments

from common.queries import get_comments_list, get_posts


def post(request, post_id):
    """ Funkcja wyświetląca posta o podanym id

    Funkcja wyświetlająca treść posta, jego oceny oraz komentarze znajdujące się pod nim (i oceny komentarzy).

    Args:
        request (WSGIRequest): obiekt klasy WSGIRequest
        post_id (int): id posta do wyświetlenia

    Returns:
        wyrenderowany kod HTML z postem

    Note:
        Pola wykorzystywane w obiekcie request:
            - .session['logged_in_as'] (str): nazwa zalogowanego użytkownika
            - .session['sort_type'] (str): typ sortowania komentarzy
    """
    try:
        post = Post.objects.get(id=post_id)
    except (Post.DoesNotExist):
        raise Http404()

    is_liked = False
    is_disliked = False
    try:
        user = User.objects.get(login=request.session['logged_in_as'])
        update_activity(user)
        if Vote.objects.filter(post=post, user=user.id, reaction=1).exists():
            is_liked = True
        if Vote.objects.filter(post=post, user=user.id, reaction=-1).exists():
            is_disliked = True
    except (KeyError, User.DoesNotExist):
        pass
    finally:
        liked = post.count_votes(reaction=1)
        disliked = post.count_votes(reaction=-1)
        context = {
            'post': post,
            'liked': liked,
            'disliked': disliked,
            'is_liked': is_liked,
            'is_disliked': is_disliked,
        }
        set_common_context(request, context)
    context['this_is_the_all_view'] = True
    context['comment_max_depth'] = comment_max_depth

    sort_types = []
    for sort_type in comment_sorting_keys:
        sort_types.append(sort_type)
    context['sort_types'] = sort_types

    selected_sort_type = request.session.get('sort_type', default='najnowsze')
    context['selected_sort_type'] = selected_sort_type

    comments = post.get_top_level_comments()
    comments_list = []
    for comm in sort_comments(comments, selected_sort_type):
        comments_list += get_comments_list(comm,
                                           selected_sort_type, context['current_user'])

    context['comments_list'] = comments_list
    context['this_is_post_view'] = True

    context['this_is_post_view'] = True

    return render(request, 'post/post.html', context)


def vote_comment(request, option):
    """ Funkcja dodająca ocenę pod komentarzem

    Funkcja dodaje lub usuwa ocenę pod komentarzem. Ocena zapisywana jest w bazie danych.
    Jeżeli użytkownik nie jest zalogowany, to ocena nie zostanie dodana/usunięta i wyrenderowana zostanie pusta strona.

    Args:
        request (WSGIRequest): obiekt klasy WSGIRequest
        option (int): wybrany rodzaj oceny, możliwe opcje:

            - 1, dodanie lajka lub usunięcie go, jeżeli lajk był dany już wcześniej
            - 2, dodanie dislajka lub usunięcie go, jeżeli dislajk był dany już wcześniej

    Returns:
        wyrenderowany kod HTML z odpowiednią oceną uzytkownika lub common/empty.html jeżeli użytkownik nie jest zalogowany

    Note:
        Pola wykorzystywane w obiekcie request:
            - .session['logged_in_as'] (str): nazwa zalogowanego użytkownika
            - .POST['comm_id'] (str): id komentarza do ocenienia
    """
    context = {}
    set_common_context(request, context)
    update_activity(context['current_user'])

    try:
        user = User.objects.get(
            login=request.session.get('logged_in_as', default=None))
    except (KeyError, User.DoesNotExist):
        return render(request, "common/empty.html", context)

    comment = get_object_or_404(Comment, id=request.POST.get('comm_id'))

    if option == 1:
        reaction = 1
    elif option == 2:
        reaction = -1
    else:
        return render(request, "common/empty.html", context)

    if CommentVote.objects.filter(user=user, comment=comment).exists():
        vote = CommentVote.objects.filter(user=user, comment=comment).first()
        if vote.get_reaction() == reaction:
            vote.delete()
        else:
            vote.reaction = reaction
            vote.save()
    else:
        vote = CommentVote(user=user, comment=comment, reaction=reaction)
        vote.save()

    is_liked = False
    is_disliked = False
    if CommentVote.objects.filter(comment=comment, user=user.id, reaction=1).exists():
        is_liked = True
    if CommentVote.objects.filter(comment=comment, user=user.id, reaction=-1).exists():
        is_disliked = True
    liked = comment.count_votes(reaction=1)
    disliked = comment.count_votes(reaction=-1)
    context = {
        'liked': liked,
        'disliked': disliked,
        'is_liked': is_liked,
        'is_disliked': is_disliked,
    }

    return render(request, 'post/likes.html', context)


def change_sorting(request):
    """ Funkcja zmieniająca rodzaj sortowania komentarzy

    Funkcja zmienia rodzaj sortowania komentarzy na wybrany przez użytkownika.
    Rodzaje sortowania są wybierane z common.comment_sorting.py (domyślnie najnowsze)

    Args:
        request (WSGIRequest): obiekt klasy WSGIRequest

    Returns:
        wyrenderowany kod HTML posta z nowym rodzajem sortowania komentarzy

    Note:
        Pola wykorzystywane w obiekcie request:
            - .POST['post_id'] (str): id aktualnie przeglądanego posta
            - .POST['sort_type'] (str): wybrany przez użytkownika (z listy) typ sortowania
            - .session['sort_type'] (str): wybrany przez użytkownika typ sortowania (zapisany w request.session)
    """
    context = {}
    set_common_context(request, context)
    update_activity(context['current_user'])

    post_id = request.POST.get('post_id', default=None)
    if not post_id:
        raise Http404()

    request.session['sort_type'] = request.POST.get(
        'sort_type', default='najnowsze')

    return redirect('post:post', post_id)


def reply(request):
    """ Funkcja dodająca komentarz pod postem lub innym komentarzem

    Funkcja dodaje komntarz pod wybranym przez użytkownika elementem (post lub komentarz).
    Nowy komentarz zapisywany jest w bazie danych, jeżeli formularz posiada prawidłowe dane.
    Jeżeli użytkownik nie jest zalogowany, to komentarz nie zostanie dodany i wyrenderowana zostanie pusta strona.

    Args:
        request (WSGIRequest): obiekt klasy WSGIRequest

    Returns:
        wyrenderowany kod HTML widoku przeglądanego posta z nowym komentarzem (o ile został dodany) lub common/empty.html jeżeli użytkownik nie jest zalogowany

    Note:
        Pola wykorzystywane w obiekcie request:
            - .session['logged_in_as'] (str): nazwa zalogowane użytkownika
            - .POST['post_id'] (str): id posta bezpośrednio pod którym ma być dodany nowy komentarz lub "None", jeżeli ma być dodany pod innym komentarzem
            - .POST['comm_id'] (str): id komentarza pod którym ma być dodany nowy komentarz lub "None", jeżeli ma być dodany bezpośrednio pod postem
            - .POST['comment'] (str): treść komentarza
    """
    context = {}
    set_common_context(request, context)
    update_activity(context['current_user'])

    parent_post = get_object_or_404(Post, id=request.POST.get('post_id'))

    text = request.POST.get("comment")
    if not text:
        raise Http404()

    try:
        author = User.objects.get(
            login=request.session.get('logged_in_as', default=None))
    except (KeyError, User.DoesNotExist):
        return render(request, "common/empty.html", context)

    comm = Comment(text=text, author=author, parent_post=parent_post)

    if not request.POST.get('comm_id'):
        raise Http404()

    if request.POST.get('comm_id') != 'None':
        comm.parent_comment = get_object_or_404(
            Comment, id=request.POST.get('comm_id'))
        if comm.get_depth() <= comment_max_depth:
            comm.save()
    else:
        comm.save()

    return redirect('post:post', parent_post.id)


def vote(request, option):
    """ Funkcja dodająca ocenę pod postem

    Funkcja dodaje lub usuwa ocenę pod postem. Ocena zapisywana jest w bazie danych.
    Jeżeli użytkownik nie jest zalogowany, to ocena nie zostanie dodana/usunięta i wyrenderowana zostanie pusta strona.

    Args:
        request (WSGIRequest): obiekt klasy WSGIRequest
        option (int): wybrany rodzaj oceny, możliwe opcje:

            - 1, dodanie lajka lub usunięcie go, jeżeli lajk był dany już wcześniej
            - 2, dodanie dislajka lub usunięcie go, jeżeli lajk był dany już wcześniej

    Returns:
        wyrenderowany kod HTML z odpowiednią oceną uzytkownika lub common/empty.html jeżeli użytkownik nie jest zalogowany

    Note:
        Pola wykorzystywane w obiekcie request:
            - .session['logged_in_as'] (str): nazwa zalogowanego użytkownika
            - .POST['post_id'] (str): id posta do ocenienia
    """
    context = {}
    set_common_context(request, context)
    update_activity(context['current_user'])

    v = Vote()
    post = get_object_or_404(Post, id=request.POST.get('post_id'))

    try:
        user = User.objects.get(
            login=request.session.get('logged_in_as', default=None))
    except (KeyError, User.DoesNotExist):
        return render(request, "common/empty.html", context)

    if Vote.objects.filter(post=post, user=user.id).exists():
        v = Vote.objects.get(post=post, user=user)

        if Vote.objects.filter(post=post, user=user.id, reaction=1).exists():
            if option == 1:
                v.delete()
            elif option == 2:
                v.reaction = -1
                v.save()

joyjoin/service/joyjoin/post/templates/post/comment.html
{% load static%}

{% if comm != ')' %}
<hr class="invisible_spacer" />
<!-- Kontener zawartosci komentarza -->
<div class="comment_content">

    <!-- Zdjecie i nazwa wyświetlana autora -->
    <a href="{% url 'user:user' comm.author.login %}" class="img_login">
        <img class="avatar" alt="awatar autora" src="{{comm.author.image_mini.url}}">
        <b>{{ comm.author.name }}</b>
        <span class="comm_creation_rel_time">{{comm.creation_rel_time}}</span>
    </a>
    <br>
    <hr class="invisible_spacer">
    {{ comm.text }}

    <hr class="visible_spacer">

    <!-- Panel komentarza -->
    <form id="comm{{comm.id}}form_like" action="{% url 'post:vote_comment' 1 %}" method="post" autocomplete="off">
        {% csrf_token %}
        <input type="hidden" name="sec_view" value="false">
        <input type="hidden" name="comm_id" value="{{comm.id}}">
    </form>

    <form id="comm{{comm.id}}form_dislike" action="{% url 'post:vote_comment' 2 %}" method="post" autocomplete="off">
        {% csrf_token %}
        <input type="hidden" name="sec_view" value="false">
        <input type="hidden" name="comm_id" value="{{comm.id}}">
    </form>

    <ul class="post_options">
        <!-- Like -->
        {% if current_user %}
            <li id="comm_like_button_{{comm.id}}" onclick="commentLike('like', {{comm.id}})">
                {% if comm_is_liked %}
                    <i class="icon-heart liked"></i> <b>{{comm_likes}}</b>
                {% else %}
                    <i class="icon-heart"></i> <b>{{comm_likes}}</b>
                {% endif %}
            </li>
        {% else %}
            <li id="login">
                <i class="icon-heart"></i> <b>{{comm_likes}}</b>
            </li>
        {% endif %}

        <!-- Unlike -->
        {% if current_user %}
            <li id="comm_dislike_button_{{comm.id}}" onclick="commentLike('dislike', {{comm.id}})">
                {% if comm_is_disliked %}
                    <i class="icon-heart-broken disliked"></i> {{comm_dislikes}}
                {% else %}
                    <i class="icon-heart-broken"></i> {{comm_dislikes}}
                {% endif %}
            </li>
        {% else %}
            <li id="login">
                <i class="icon-heart-broken"></i> {{comm_dislikes}}
            </li>
        {% endif %}

        <!-- Komentarz -->
        {% if current_user %}
            <li id="comm{{comm.id}}button_reply">
                <i class="icon-comment"></i>
                <i class="votes_number">({{comm.count_all_replies}})</i>
            </li>
        {% else %}
            <li id="login">
                <i class="icon-comment"></i>
                <i class="votes_number">({{comm.count_all_replies}})</i>
            </li>
        {% endif %}

        <!-- Zgłoszenie -->
        <li>
            <i class="icon-hammer"></i>
        </li>
    </ul>

</div>

<!-- Kontener pod komentarzem -->
<div id="comm{{comm.id}}under_comment" {% if comm.count_direct_replies == 0 %}hidden{% endif %}>

    <table>
        <tr>

            <!-- Panel po lewej stronie odpowiedzi -->
            <td class="left_spacer">
                <!-- PRZYCISK do chowania odpowiedzi -->
                <button id="comm{{comm.id}}button_hide_replies" class="hide_replies"></button>
            </td>

            <td class="right_spacer">
                <!-- Kontener panelu odpowiedzi -->
                {% if current_user %}
                    {% if not comm.is_max_depth %}
                    <div hidden=true id="comm{{comm.id}}reply_panel" class="reply_panel">
                        <a href="{% url 'user:user' current_user.login %}" class="img_login">
                            <img src="{{current_user.image_mini.url}}" >
                            <b>{{ current_user.name }}</b>
                        </a>

                        <form action="{% url 'post:reply' %}" method="post" autocomplete="off">
                            {% csrf_token %}
                            <input type="hidden" name="post_id" value="{{post.id}}">
                            <input type="hidden" name="comm_id" value="{{comm.id}}">
                            <textarea name="comment" required placeholder="Napisz komentarz..."></textarea>
                            <input type="submit" value="Dodaj komentarz">
                        </form>
                    </div>
                    {% else %}
                        <i hidden=true id="comm{{comm.id}}reply_panel" class="warning">
                            Osiągnięto maksymalną głebokość komentarza ({{comment_max_depth}}).
                        </i>
                    {% endif %}

                {% endif %}

                <!-- PRZYCISK do pokazywania odpowiedzi -->
                <button id="comm{{comm.id}}button_show_replies" hidden=true class="show_replies">Pokaz odpowiedzi</button>

                <!-- Kontener odpowiedzi -->
                <div id="comm{{comm.id}}replies">
{% else %}

                </div>
            </td>

        </tr>



    </table>

</div>

{% endif%}

<script>
    document.getElementById("comm{{comm.id}}button_hide_replies").addEventListener("click", function() {
        document.getElementById("comm{{comm.id}}replies").hidden = true;
        document.getElementById("comm{{comm.id}}button_hide_replies").hidden = true;
        document.getElementById("comm{{comm.id}}button_show_replies").hidden = false;
        document.getElementById("comm{{comm.id}}reply_panel").hidden = true
    }, false);
    document.getElementById("comm{{comm.id}}button_show_replies").addEventListener("click", function() {
        document.getElementById("comm{{comm.id}}replies").hidden = false;
        document.getElementById("comm{{comm.id}}button_hide_replies").hidden = false;
        document.getElementById("comm{{comm.id}}button_show_replies").hidden = true;
    }, false);

    document.getElementById("comm{{comm.id}}button_reply").addEventListener("click", function() {
        document.getElementById("comm{{comm.id}}replies").hidden = false;
        document.getElementById("comm{{comm.id}}button_hide_replies").hidden = false;
        document.getElementById("comm{{comm.id}}button_show_replies").hidden = true;

        if (document.getElementById("comm{{comm.id}}reply_panel").hidden == true) {
            // otworzenie panelu odpowiedzi
            document.getElementById("comm{{comm.id}}under_comment").hidden = false;
            document.getElementById("comm{{comm.id}}reply_panel").hidden = false;
            {% if comm.count_direct_replies == 0 %}
             document.getElementById("comm{{comm.id}}button_hide_replies").hidden = true
            {% endif %};
        }
        else {
            // zakmniecie panelu odpowiedzi
            document.getElementById("comm{{comm.id}}reply_panel").hidden = true;
             {% if comm.count_direct_replies == 0 %}
             document.getElementById("comm{{comm.id}}under_comment").hidden = true
             {% endif %};
        }
    }, false);

</script>

joyjoin/service/joyjoin/post/templates/post/likes.html
{% if is_liked %}
    <i class="icon-heart liked"></i> <b>{{liked}}</b>
{% else %}
    <i class="icon-heart"></i> <b>{{liked}}</b> 
{% endif %}
<br>
{% if is_disliked %}
    <i class="icon-heart-broken disliked"></i> {{disliked}}
{% else %}
    <i class="icon-heart-broken"></i> {{disliked}} 
{% endif %}

joyjoin/service/joyjoin/post/templates/post/new_posts.html
{% for post,liked,disliked,is_liked,is_disliked,comments in posts_to_display %}
    {% include 'post/single_post.html' %}
{% endfor%}

joyjoin/service/joyjoin/post/templates/post/post.html
{% extends 'common/frame.html' %}
{% load static %}

	{% block sscss %}
	<link href="{% static 'post/post.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'post/comment.css' %}" rel="stylesheet" type="text/css">
	{% endblock %}

		{% block ssc %}
		<div id="content">
			{% include 'post/single_post.html' %}
		</div>
		{% endblock %}

joyjoin/service/joyjoin/post/templates/post/single_post.html
{% load static %}


{% if this_is_post_view %}
<div id="goback"> <p> <a href="javascript:history.back();"><i class="icon-angle-double-left"></i>Powrót</a> </p> </div>
{% endif %}

<div class="post">
	<div class="header">
		<a href="{% url 'user:user' post.author.login %}"> <img class="avatar" alt="awatar autora" src="{{post.author.image_mini.url}}"> </a>
		<div class="sender">
			<a href="{% url 'user:user' post.author.login %}" class="name">{{ post.author.name }}</a> <br>
		<span class="post_creation_rel_time">{{ post.creation_rel_time }}</span><br>
		{% if this_is_the_all_view %}
			<a href="{% url 'sec:section' post.section.name %}" class="link-section"><i class="icon-{{post.section.icon}}"></i>{{post.section.description}}</a>
		{% endif %}
		</div>
	</div>

	{% if this_is_create_view %}
		Tagi: <input id="tag_input"></input>
	{% elif post.tags.all or post.implied_tags.all or post.user_tags_as_list %}
	<div class="tags">
	{% for tag in post.tags.all %}
		<a
			class='tag'
			href="{% url 'sec:section' post.section.name %}?tag={{ tag.slug_or_name }}"
			title="{{ tag.tooltip }}"
		>{{ tag.name}}</a>
	{% endfor %}
	{% for tag in post.implied_tags.all %}
		<a
			class='implied_tag'
			href="{% url 'sec:section' post.section.name %}?tag={{ tag.slug_or_name }}"
			title="{{ tag.tooltip }}"
		>{{ tag.name}}</a>
	{% endfor %}
	{% for tag in post.user_tags_as_list %}
		<a class='usertag' href="{% url 'sec:section' post.section.name %}?tag={{ tag|urlencode }}">{{ tag }}</a>
	{% endfor %}
	</div>
	{% endif %}

	<a {% if not this_is_post_view and not this_is_create_view %}href="{% url 'post:post' post.id %}"{% endif %} class="title" {% if this_is_create_view %} id="preview_post_title" contenteditable {% endif %}>{{ post.title }}</a>
	<div id="post_text_{{post.id}}" class="post_text {% if not this_is_post_view and not this_is_create_view %} abbreviated {% endif %}">
		{% if not this_is_create_view %}
			<p {% if this_is_create_view %} contenteditable {% endif %}>
				{% autoescape off %}
					{{ post.text }}
				{% endautoescape %}
			</p>
		{% else %}
			<div id="quill"></div>
		{% endif %}
	</div>

	{% if not this_is_post_view and not this_is_create_view %}
		<a id="see_more_{{post.id}}" class="see-more" onclick="show_full_post({{post.id}})">Zobacz więcej<i class="icon-down-dir-2"></i></a>
	{% endif %}

	<hr>
	<div class="feedback">
		<form id="like_form_{{post.id}}" action="{% url 'post:vote' 1 %}" method="post">
			{% csrf_token %}
			<input type="hidden" name="post_id" value="{{post.id}}">
		</form>
		<form id="dislike_form_{{post.id}}" action="{% url 'post:vote' 2 %}" method="post">
			{% csrf_token %}
			<input type="hidden" name="post_id" value="{{post.id}}">
		</form>

		<ul class="post_options">
			<li onclick="like('like', {{post.id}});">
				<span id="like_button_{{post.id}}">
					{% if is_liked %}
						<i class="icon-heart liked"></i> <b>{{liked}}</b>
					{% else %}
						<i class="icon-heart"></i> <b>{{liked}}</b>
					{% endif %}
				</span>
			</li>
			<li onclick="like('dislike', {{post.id}});">
				<span id="dislike_button_{{post.id}}">
					{% if is_disliked %}
						<i class="icon-heart-broken disliked"></i> {{disliked}}
					{% else %}
						<i class="icon-heart-broken"></i> {{disliked}}
					{% endif %}
				</span>
			</li>
			{% if current_user %}
				<li id="post{{post.id}}button_reply"> <i class="icon-comment"></i> Skomentuj </li>
			{% else %}
				<li id="login"> <i class="icon-comment"></i> Skomentuj </li>
			{% endif %}
			<li> <i class="icon-hammer"></i> Zgłoś </li>
		</ul>
	</div>

	<!-- Kontener komentarzy -->
	{% if not this_is_create_view %}
	<div class="comments">
		<hr>
		{% if this_is_post_view %}
			<form action="{% url 'post:change_sorting' %}" method="post" autocomplete="off">
				{% csrf_token %}
				Sortuj po:
				<input hidden name='post_id' value={{post.id}}>
				<select name="sort_type" onchange="submit()">
					{% for type in sort_types %}
						<option value="{{type}}"{% if type == selected_sort_type %} selected{% endif %}>{{type}}</option>
					{% endfor %}
				</select>
			</form>
		{% endif %}

		{% if current_user %}
			<!-- Kontener panelu odpowiedzi -->
			<div hidden id="post{{post.id}}reply_panel" class="reply_panel">
				<a href="{% url 'user:user' current_user.login %}" class="img_login">
					<img alt="awatar użytkownika" src="{{current_user.image_mini.url}}">
					<b>{{ current_user.name }}</b>
				</a>

				<form action="{% url 'post:reply' %}" method="post" autocomplete="off">
					{% csrf_token %}
					<input type="hidden" name="post_id" value="{{post.id}}">
					<input type="hidden" name="comm_id" value="None">
					<textarea name="comment" required placeholder="Napisz komentarz..."></textarea>
					<input type="submit" value="Dodaj komentarz">
				</form>
			</div>
		{% endif %}

		{% if post.count_all_comments > 0 %}
			{% if this_is_post_view %}					
				{% for comm, comm_likes, comm_dislikes, comm_is_liked, comm_is_disliked in comments_list %}
					{% include 'post/comment.html' %}
				{% endfor %}
			{% else %}
				{% include 'post/simple_comment.html' %}
			{% endif %}
		{% endif %}
	</div>
	{% endif %}
</div>

<!-- Skrypt do obslugi przycisku "Skomentuj" -->
<script>
	document.getElementById("post{{post.id}}button_reply").addEventListener("click", function() {
			if (document.getElementById("post{{post.id}}reply_panel").hidden == true) {
				// otworzenie panelu odpowiedzi
				document.getElementById("post{{post.id}}reply_panel").hidden = false;
			}
			else {
				// zakmniecie panelu odpowiedzi
				document.getElementById("post{{post.id}}reply_panel").hidden = true;
			}
		}, false);
</script>