joyjoin/service/joyjoin/all/urls.py
from django.urls import path

from . import views
from sec.views import preferences

app_name = 'all'

urlpatterns = [
    path('', views.all, name='all'),
    path('404devel', views.error_404, name='404devel'),
    path('preferences', preferences, name='preferences'),
]

joyjoin/service/joyjoin/joyjoin/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from all import views as all_views
import all

urlpatterns = [
    path('', all.views.about, name='about'),
    path('admin/', admin.site.urls),
    path('register/', include('register.urls')),
    path('login/', include('login.urls')),
    path('create/', include('create.urls')),
    path('user/', include('user.urls')),
    path('sec/', include('sec.urls')),
    path('all/', include('all.urls')),
    path('settings/', include('settings.urls')),
    path('post/', include('post.urls')),
    path('report/', include('report.urls')),
    path('rules/', all.views.regulamin, name='rules'),
]
handler404 = all_views.error_404
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

joyjoin/service/joyjoin/login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login, name='login'),
    path('verify/', views.verify, name='verify'),
    path('logout/', views.logout, name='logout'),
]

joyjoin/service/joyjoin/register/urls.py
from django.urls import path

from . import views

app_name = 'register'

urlpatterns = [
    path('', views.register, name='register'),
    path('complete/', views.complete, name='complete'),
    path('is_login_unused/', views.is_login_unused, name='is_login_unused'),
    path('is_password_uncommon/', views.is_password_uncommon, name='is_password_uncommon'),
    path('is_age_ok/', views.is_age_ok, name='is_age_ok'),
]

joyjoin/service/joyjoin/report/urls.py
from django.urls import path

from . import views

app_name = 'report'

urlpatterns = [
    path('', views.report, name='report'),
    path('add/', views.add, name='add'),
]

joyjoin/service/joyjoin/sec/urls.py
from django.urls import path

from . import views

app_name = 'sec'

urlpatterns = [
    path('<str:section_name>/', views.section, name='section'),
    path('<str:section_name>/tags/', views.tags, name='tags'),
    path('join/<str:section_name>/', views.join, name='join'),
    path('leave/<str:section_name>/', views.leave, name='leave'),
    path('<str:section_name>/preferences/',
         views.preferences, name='preferences'),
    path('<str:section_name>/update_punctation/',
         views.update_punctation, name='update_punctation'),
]

joyjoin/service/joyjoin/user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('<str:username>/', views.user, name='user'),
]

joyjoin/service/joyjoin/common/models.py
import datetime
import re

from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.core.validators import EmailValidator
from django.db import models, transaction
from django.utils import timezone
from django.utils.dateparse import parse_date

from common.relative_time import relative_time
from common.sanitizer import is_sanitary


class User(models.Model):
    """ Klasa reprezentująca użytkownika.

    Attributes:
        login (str): login użytkownika, używany do logowania i widoczny w URLach
        password (str): hasło użytkownika, przechowywane jako skrót PBKDF2
        email (str): adres email użytkownika, obecnie jeszcze nieużywany w praktyce
        birth_date (datetime.date): data urodzenia użytkownika
        creation_time (datetime.datetime): czas utworzenia modelu tego użytkownika w bazie danych
        description (str): opis własny użytkownika, użytkownik może go edytować i wyświetla się na jego stronie
        last_activity_time (datetime.datetime): czas ostatniej aktywności użytkownika
        last_update_punctation_time (datetime.datetime): czas ostatniej aktualizacji punktacji w tabeli TagPunctation dla danego użytkownika
        is_punctation_changeable (bool): True, gdy użytkownik zezwala na modyfikację punktacji w tabeli TagPunctation, False wpw.
    """
    login = models.CharField(max_length=31, unique=True)
    password = models.CharField(max_length=511)
    email = models.CharField(max_length=127)
    name = models.CharField(max_length=63)
    birth_date = models.DateField()
    creation_time = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=511, blank=True)
    last_activity_time = models.DateTimeField(auto_now_add=True)
    last_update_punctation_time = models.DateTimeField(auto_now_add=True)
    is_punctation_changeable = models.BooleanField(default=True)
    image = models.ImageField(
        default='default.jpg', width_field="width_field", height_field="height_field")
    image_mini = models.ImageField(default='default_mini.jpg')
    height_field = models.IntegerField(null=True)
    width_field = models.IntegerField(null=True)

    def __str__(self):
        return self.login

    def save(self, *args, **kwargs):
        """
        Sprawdza poprawność modelu użytkownika.
        Jeśli model jest poprawny, zapisuje go w bazie.
        Jeśli tworzony jest nowy model użytkownika to dla każdego istniejącego tagu dodaje rekord w tabeli TagPunctation z punktacjami nowego użytkownika.
        Jeśli model nie jest poprawny zwraca django.core.expections.ValidationError
        """
        data = {
            'login': self.login,
            'password': self.password,
            'email': self.email,
            'name': self.name,
            'birth_date': self.birth_date,
            'creation_time': self.creation_time,
            'description': self.description,
            'last_activity_time': self.last_activity_time,
        }
        result = User.validate(data, source='model')
        if result[0] == 'OK':
            with transaction.atomic():
                super().save(*args, **kwargs)

                # Jezeli tworzony jest nowy użytkownik to dodaje nowe rekordy do tabeli TagPunctation
                if not TagPunctation.objects.filter(user=self).exists():
                    for tag in Tag.objects.all():
                        tp = TagPunctation()
                        tp.user = self
                        tp.tag = tag
                        tp.punctation = 0
                        tp.save()
        else:
            raise ValidationError(
                'Nie można zapisać modelu: {}'.format(result[1]))

    def validate(data, source='register'):
        """
        Sprawdza czy przekazane dane są poprawne.
        Zwraca listę dwuelemntową:
            * jeśli walidacja przebiegła poprawnie pierwszy element listy to 'OK'
            * w przeciwnym wypadku, pierwszy element listy to inny niepusty string
            * drugi element listy to przyjazny dla człowieka opis
        Parametr 'source' określa rodzaj walidacji:
            'model': oznacza, że walidacja sprawdza czy dane modelu są poprawne i mogą być zapisane
            'register': wartość domyślna, oznaczna że walidowane są dane przy rejestracji
            'settings': oznacza że walidadowane są dane z aplikacji settings
        """

        # Sprawdza czy źródło jest jedną z prawidłowych wartości
        if source not in ['model', 'register', 'settings']:
            raise ValueError

        try:
            login = data['login']
            name = data['name']
            email = data['email']
            if source == 'model':
                password = data['password']
            elif source in ['register', 'settings']:
                passwd1 = data['password']
                passwd2 = data['password_2']
            if source == 'model':
                birth_date = data['birth_date']
            elif source in ['register', 'settings']:
                date_string = data['birth_date']
            if source == 'model':
                creation_time = data['creation_time']
            if source in ['model', 'settings']:
                description = data['description']
            if source == 'model':
                last_activity_time = data['last_activity_time']
            if source == 'register':
                acceptance = data['rules']
        except KeyError:
            return ['post_error', 'Błąd POST']

        # Sprawdzanie poprawności i unikalności loginu
        if not 3 <= len(login) <= 20:
            return ['login_wrong_length', 'Login musi mieć od 3 do 20 znaków']

        for letter in login:
            if not (letter.islower() or letter.isnumeric() or letter == '_'):
                return ['login_forbidden_characters', 'Login musi się składać wyłącznie z małych liter, cyfr lub znaku "_"']

        if not login[0].islower():
            return ['login_forbidden_first_character', 'Login musi zaczynać się od litery']

        if source == 'register':
            for user in User.objects.all():
                if user.login == login:
                    return ['login_used', 'Login jest już zajęty']

        # Sprawdzanie imienia i nazwiska (nazwy)
        if not 3 <= len(name) <= 63:
            return ['name_wrong_length', 'Imię i nazwisko muszą mieć od 3 do 63 znaków']

        for letter in name:
            if not (letter.isalpha() or letter == ' '):
                return ['name_forbidden_characters', 'Imię i nazwisko muszą składać się tylko z liter']

        # Sprawdzanie adresu email
        email_validator = EmailValidator()
        try:
            email_validator(email)
        except ValidationError:
            return ['email_wrong_format', 'Błędny adres email']

        # Sprawdzanie hasła
        if source == 'register' or (source == 'settings' and (passwd1 or passwd2)):
            if passwd1 != passwd2:
                return ['password_different_passwords', 'Hasła nie są identyczne']
            try:
                validate_password(passwd1)
            except ValidationError as errors:
                for error in errors:
                    if error.startswith('To hasło jest za krótkie. Musi zawierać co najmniej 8 znaków.'):
                        return ['password_too_short', 'Hasło jest za krótkie. Musi zawierać minimum 8 znaków.']
                    if error.startswith('To hasło jest zbyt powszechne.'):
                        return ['password_too_common', 'Hasło jest zbyt proste.']
                    if error.startswith('Hasło składa się wyłącznie z cyfr.'):
                        return ['password_is_numeric', 'Hasło nie może składać się tylko z cyfr.']
        elif source == 'model':
            regex = re.compile(
                'pbkdf2_sha256\\$[1-9][0-9]*\\$[a-zA-Z0-9+/]+(=){0,2}\\$[a-zA-Z0-9+/]+(=){0,2}$')
            if not regex.fullmatch(password):
                return ['password_improperly_formated', 'Hasło jest źle sformatowane']

        # Sprawdzanie daty
        if source in ['register', 'settings']:
            try:
                date = parse_date(date_string)
            except ValueError:
                return ['age_wrong_format', 'Zły format daty']
            if date is None:
                return ['age_wrong_format', 'Zły format daty']
            age = timezone.now().date() - date
        elif source == 'model':
            if type(birth_date) == str:
                birth_date = parse_date(birth_date)
            age = timezone.now().date() - birth_date
        if not 12 * 365.25 <= age.days <= 120 * 365.25:
            return ['age_wrong_date', 'Musisz być w wieku między 12 a 120 lat aby założyć konto']

        # Sprawdzanie czasu utworzenia
        if source == 'model':
            if creation_time is not None:
                if creation_time > timezone.now():
                    return ['creation_time_in_the_future', 'Czas utworzenia użytkownika jest w przyszłości']
                if creation_time.date() < birth_date:
                    return ['creation_time_before_birth', 'Czas utworzenia użytkownika jest przed jego narodzeniem']

        # Sprawdzanie opisu
        if source in ['model', 'settings'] and description is not None and len(description) > 511:
            return ['description_too_long', 'Opis nie może być dłuższy niż 511 znaków.']

        # Sprawdzanie czasu ostatniej aktywności
        if source == 'model':
            if last_activity_time is not None:
                if last_activity_time > timezone.now():
                    return ['last_activity_time_in_the_future', 'Czas ostatniej aktywności użytkownika jest w przyszłości']
                if last_activity_time < creation_time:
                    return ['creation_time_before_creation', 'Czas ostatniej aktywności użytkownika jest przed utworzeniem użytkownika']
        # Sprawdzanie akceptacji regulaminu

joyjoin/service/joyjoin/register/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.utils.dateparse import parse_date
from django.contrib.auth.hashers import make_password
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.utils import timezone

from common.context import set_common_context
from common.models import User
from common.activity import update_activity


def register(request):
    """ Jest to funkcja, która przedstawia stronę zawierającą formularz rejestracji dla użytkownika

    Args:
        request(WSGIRequest):obiekt klasy WSGIRequest

    Returns:
        django.http.HtttpResponse:obiekt reprezentujący wyrenderowany widok 'register/register.html' z ustawionym kontekstem szablonu
    """
    context = {}
    set_common_context(request, context)
    update_activity(context['current_user'])
    context['is_register_site'] = True
    if context['current_user'] is not None:
        return redirect('all:all')
    else:
        return render(request, 'register/register.html', context)


def complete(request):
    """ Funkcja kompletująca rejestrację użytkownika.

    Args:
        request(WSGIRequest):obiekt klasy WSGIRequest

    Returns:
        django.http.HtttpResponse:zwraca przekierowanie do adresu 'register/register.html'
    """
    data = request.POST

    # Dokonaj sprawdzenia poprawności danych
    result = User.validate(data)

    if result[0] != 'OK':
        # Zwroc negatywna odpowiedz
        messages.add_message(request, messages.ERROR,
                             result[1], extra_tags=result[0])
    else:
        # Skonstruuj obiekt klasy 'User'
        user = User()
        user.name = data['name']
        user.login = data['login']
        user.email = data['email']
        user.password = make_password(data['password'])
        user.birth_date = parse_date(data['birth_date'])
        # TODO user powinien być oznaczony jako nieaktywny dopóki nie odbierze maila

        # Zapisz obiekt w bazie
        user.save()

        # Zwroc pozytywna odpowiedz
        messages.add_message(request, messages.SUCCESS,
                             result[1], extra_tags=result[0])
    return redirect('register:register')


def is_login_unused(request):
    try:
        login = request.POST["login"]
    except KeyError:
        return HttpResponse("false")

    if not login:
        return HttpResponse("false")

    if User.objects.filter(login=login).exists():
        return HttpResponse("false")
    else:
        return HttpResponse("true")


def is_password_uncommon(request):
    try:
        password = request.POST["password"]
    except KeyError:
        return HttpResponse("false")

    if not password:
        return HttpResponse("false")

    try:
        validate_password(password)
    except ValidationError as errors:
        for error in errors:
            if error.startswith('To hasło jest zbyt powszechne.'):
                return HttpResponse("false")
    return HttpResponse("true")


def is_age_ok(request):
    try:
        date_string = request.POST["date"]
    except KeyError:
        return HttpResponse("false")

    try:
        date = parse_date(date_string)
    except ValueError:
        return HttpResponse("false")
    if date is None:
        return HttpResponse("false")
    age = timezone.now().date() - date
    if not 12 * 365.25 <= age.days <= 120 * 365.25:
        return HttpResponse("false")
    return HttpResponse("true")

joyjoin/service/joyjoin/common/templates/common/frame.html
{% load static %}
<!DOCTYPE HTML>
<html lang="pl">
<head>
    <!-- Podstawowe meta tagi -->
	<meta charset="utf-8">
	<title>JoyJoin</title>
	<link rel="Shortcut icon" href="{% static 'common/img/logo/jjicon.png' %}"/>
	<meta name="desription" content="Opis">
	<meta name="keywords" content="Słowa kluczowe">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Linki do plikow css, ikon, czcionek -->
    <link href="{% static 'common/styles/common.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'common/styles/register_form.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'common/styles/tags.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'common/fonts/fontello/css/fontello.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Gelasio&display=swap" rel="stylesheet">
    
    <link href="{% static 'common/styles/responsivness.css' %}" rel="stylesheet" type="text/css">
    
    {% block sscss %} {# (site-specific CSS) Przy użyciu tego bloku można dodać arkusze stylu CSS do konkretnej strony #} {% endblock %}
</head>

<body>
    <div id="navbar"{% if not this_is_section_view %}class="navbar-color"{% endif %}>
        <div>
            <a href="{% url 'all:all' %}"><img id="logo" src="{% static 'common/img/logo/jj300x90.png' %}" alt="logo"></a>
            <form>
                <!-- TODO <input type="text" placeholder="szukaj">
                <button id="find"> <i class="icon-search"></i> </button>-->
            </form>
        </div>
        <div>
            {% if current_user %}
                <div id="account">
                    <span id="user_name">{{ current_user.name }}</span> <img class="avatar" alt="Twój awatar" src="{{ current_user.image_mini.url}}">
                </div>
            {% else %}
                {% if not is_register_site %}
                    <button id="register"> <i class="icon-user-plus"></i> Zarejestruj </button>
                {% endif %}
                <button id="login"> <i class="icon-user"></i> Zaloguj </button>
            {% endif %}
            <i id="menu_icon" class="icon-menu" onclick="show_mobile_menu()"></i>
        </div>
    </div> <!-- Koniec #navbar -->

    {% if current_user %}
        <div id="account-window">
            <ul>
                <li> <a href="{% url 'user:user' current_user.login %}"> <i class="icon-user-1"></i> Zobacz profil</a> <hr> </li>
                <!--TODO <li> <a href=""> <i class="icon-mail-alt"></i> Wiadomości</a> <hr> </li>
                <li> <a href=""> <i class="icon-bell-alt"></i> Powiadomienia</a> <hr> </li> -->
                <li> <a href="{% url 'settings:settings' %}"> <i class="icon-cog"></i> Ustawienia</a> <hr> </li>
                <li> <a href="{% url 'report:report' %}"> <i class="icon-cancel-2"></i> Zgłoś błąd</a> <hr> </li>
                <li> <a href="{% url 'login:logout' %}"> <i class="icon-off"></i> Wyloguj</a> </li>
            </ul>
        </div> <!-- Koniec #account-window -->
    {% else %}
        <div id="login-window">
            <form action="{% url 'login:verify' %}" method="post" autocomplete="on">
            {% csrf_token %}
                <input name="login" type=text required placeholder="Login lub e-mail"><br>
                <input name="password" type=password required placeholder="Hasło"><br>
                <!-- TODO <label> <input name="remember" type="checkbox"> Zapamietaj mnie</label> <br> -->
                <input type="submit" value=Zaloguj>
            </form>
        </div> <!-- Koniec #login-window -->
    
        <div id="dark-screen"></div>
        {% if not is_register_site %}
            <div id="register-window">
                <i id="register-exit" class="icon-cancel"></i>
                {% include 'common/register_form.html' %}
            </div>
        {% endif %}
    {% endif %}

    {% block hero-image %} {# tu mozna dodac hero-image (tylko w /all) #} {% endblock %}

    <div id="mobile_menu">
    </div>

    <div id="site">
        <div id="left_placeholder" class="placeholder">
            <div id="left-menu">
                {% if current_user %}
                    {% if user_sections %}
                    <ul>
                        <li>Twoje sekcje<hr></li>
                        {% for sec in user_sections %}
                            <li> <a {% if sec.name == current_section_name %}class="selected"{% endif %} href="{% url 'sec:section' sec.name %}"> <i class="icon-{{sec.icon}}"></i> {{ sec.description }}</a> <hr> </li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    {% if recommended_sections %}
                    <ul>
                        <li>Lista sekcji<hr></li>
                        {% for sec in recommended_sections %}
                            <li> <a {% if sec.name == current_section_name %}class="selected"{% endif %} href="{% url 'sec:section' sec.name %}"> <i class="icon-{{sec.icon}}"></i> {{ sec.description }}</a> <hr> </li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                {% else %}
                    <ul>
                        <li>Lista sekcji<hr></li>
                        {% for sec in popular_sections %}
                            <li> <a {% if sec.name == current_section_name %}class="selected"{% endif %} href="{% url 'sec:section' sec.name %}"> <i class="icon-{{sec.icon}}"></i> {{ sec.description }}</a> <hr> </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div> <!-- Koniec #left-menu -->
        </div> <!-- Koniec .placeholder -->

       <div id="right_placeholder" class="placeholder">
            <div id="right-menu">
                
                <ul id="available-options">
                    <li>Dostępne opcje</li>
                    {% block available-options %} {# tutaj można dodać dostępne opcje #} {% endblock %}
                    <li> <a href="{% url 'report:report' %}">Zgłoś błąd</a> </li>
                </ul>
                
                {% block right-menu %} {# tutaj można dodać rzeczy widoczne w right-menu #} {% endblock %}

                <a href="https://brave.com/joy155" target="_blank">
                    <img id="banner" src="{% static 'common/img/brave_banner.png' %}" alt="banner"><hr>
                </a>

                <div id="footer">
                    <a href="https://aleks-2.mat.umk.pl/pz2019/zesp08/" target="_blank">O nas</a>
                    <a onclick="showcontact()">Kontakt</a>
                    <a href="{% url 'rules' %}">Regulamin</a> <br><br>
                    <div class="kontakt">
                        Zespół JoyJoin <br>
                        joyjoin.team@gmail.com<br><br>
                    </div>                    Zespół VIII Wydział Matematyki i Informatyki UMK © copyright 2019-2020
                </div>
            </div>
        </div> <!-- Koniec #right-menu -->
        
        {% block ssc %} {# ssc od site specific content #}
        {# tutaj wstawiamy zawartość strony #}
        {% endblock %}
    </div> <!-- Koniec #site -->

    <!-- Linki do bibliotek JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{% static 'common/scripts/scripts.js' %}" type="text/javascript"></script>
    <script src="{% static 'common/scripts/register_form.js' %}" type="text/javascript"></script>
    {% block ssjs %} {# (site-specific JS) Przy użyciu tego bloku można dodać pliki JavaScript do konkretnej strony #} {% endblock %}
    
    {% block forms %} {# Tutaj można dodawać formularze, które będę wysyłane za pomocą ajax #} {% endblock %}

</body>
</html>

joyjoin/service/joyjoin/common/templates/common/register_form.html
<div id="register_form">
    <h1>Rejestracja</h1>
    {% if messages %}
        <ul id="messages">
            {% for msg in messages %}
                <li {% if msg.tags %} class="{{ msg.tags }}" {% endif %}>
                    {{ msg }}
                </li>
            {% endfor %}
        </ul>

    {% endif %}

    <!-- Formy do przesyłu wiadomości przez ajax -->
    <form id="rpf_login_request" action="{% url 'register:is_login_unused' %}" method="post" autocomplete="on">
    {% csrf_token %}
    <input id="rpf_login_request_input" name="login" type="hidden">
    </form>

    <form id="rpf_password_request" action="{% url 'register:is_password_uncommon' %}" method="post" autocomplete="on">
    {% csrf_token %}
    <input id="rpf_password_request_input" name="password" type="hidden">
    </form>

    <form id="rpf_date_request" action="{% url 'register:is_age_ok' %}" method="post" autocomplete="on">
    {% csrf_token %}
    <input id="rpf_date_request_input" name="date" type="hidden">
    </form>

    <!-- Formularz rejestracji i warningi -->
    <form id="register_panel_form" action="{% url 'register:complete' %}" method="post" autocomplete="on">
        {% csrf_token %}
        <input id="rpf_login" name="login" type="text" required placeholder="Nazwa użytkownika"> 
        <div class="warning" id="warning_panel_rpf_login">
            <label id="rpf_login_empty"> pole nie może być puste </label>
            <label  id="rpf_login_used"> login jest już zajęty </label>
            <hr id="rpf_login_bad_length_hr">
            <label id="rpf_login_bad_length"> login musi mieć 3 do 20 znaków </label>
            <hr id="rpf_login_first_letter_hr">
            <label id="rpf_login_first_letter"> login musi zaczynać się od litery </label>
            <hr id="rpf_login_bad_character_hr">
            <label id="rpf_login_bad_character"> login może zawierać jedynie małe litery i liczby </label>
        </div>               
        <br>

        <input id="rpf_name" name="name" type="text" required placeholder="Imię i nazwisko"> 
        <div class="warning" id="warning_panel_rpf_name">
            <label id="rpf_name_empty"> pole nie może być puste </label>
            <hr id="rpf_name_bad_length_hr">
            <label id="rpf_name_bad_length"> imię i nazwisko muszą mieć od 3 do 63 znaków </label>
            <hr id="rpf_name_bad_character_hr">
            <label id="rpf_name_bad_character"> imię i nazwisko mogą zawierać jedynie litery i spacje </label>
        </div>               
        <br>

        <input id="rpf_email" name="email" type=email required placeholder="E-mail">
        <div class="warning" id="warning_panel_rpf_email">
            <label id="rpf_email_empty"> pole nie może być puste </label>
            <label id="rpf_email_bad"> adres email nieprawidłowy </label>
        </div> 
        <br>

        <input id="rpf_password" name="password" type=password required placeholder="Hasło">
        <div class="warning" id="warning_panel_rpf_password">
            <label id="rpf_password_empty"> pole nie może być puste </label>
            <label id="rpf_password_short"> hasło musi mieć co najmniej 8 znaków </label>
            <hr id="rpf_password_numeric_hr">
            <label id="rpf_password_numeric"> hasło nie może składać się tylko z cyfr </label>
            <label id="rpf_password_too_common"> hasło zbyt proste </label>
        </div> 
        <br>

        <input id="rpf_password2" name="password_2" type=password disabled required placeholder="Powtórz hasło">
        <div class="warning" id="warning_panel_rpf_password2">
            <label id="rpf_password2_empty"> pole nie może być puste </label>
            <label id="rpf_password2_different"> hasło różni się od pierwszego </label>
        </div> 
        <br>
        
        {% comment "Na razie nie zbieramy takich informacji" %}
        <select name="gender">
                <option disabled selected>Płeć</option>
                <option>Meżczyzna</option>
                <option>Kobieta</option>
        </select><br>
        {% endcomment %}
        
        <input id="rpf_birth_date" name="birth_date" type="date">
        <div class="warning" id="warning_panel_rpf_birth_date">
            <label id="rpf_birth_date_empty"> należy podać datę urodzenia </label>
            <label id="rpf_birth_date_age"> musisz być w wieku między 12 a 120 lat aby założyć konto </label>
        </div> 
        <br>

        <input id="rpf_rules" name="rules" type="checkbox" required>
        <span id="accept_rules">Akceptuję regulamin</span>
        <div class="warning" id="warning_panel_rpf_rules">
            <label id="rpf_rules_empty"> należy zaakceptować regulamin </label>
        </div> 
        <br>

        <input id="rpf_submit" type="button" value="REJESTRUJ" onclick="form_submit()">
    </form>
</div>