joyjoin/service/joyjoin/all/urls.py
from django.urls import path

from . import views
from sec.views import preferences

app_name = 'all'

urlpatterns = [
    path('', views.all, name='all'),
    path('404devel', views.error_404, name='404devel'),
    path('preferences', preferences, name='preferences'),
]

joyjoin/service/joyjoin/joyjoin/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from all import views as all_views
import all

urlpatterns = [
    path('', all.views.about, name='about'),
    path('admin/', admin.site.urls),
    path('register/', include('register.urls')),
    path('login/', include('login.urls')),
    path('create/', include('create.urls')),
    path('user/', include('user.urls')),
    path('sec/', include('sec.urls')),
    path('all/', include('all.urls')),
    path('settings/', include('settings.urls')),
    path('post/', include('post.urls')),
    path('report/', include('report.urls')),
    path('rules/', all.views.regulamin, name='rules'),
]
handler404 = all_views.error_404
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

joyjoin/service/joyjoin/report/urls.py
from django.urls import path

from . import views

app_name = 'report'

urlpatterns = [
    path('', views.report, name='report'),
    path('add/', views.add, name='add'),
]

joyjoin/service/joyjoin/user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('<str:username>/', views.user, name='user'),
]

joyjoin/service/joyjoin/report/models.py
from django.db import models
from common.models import User
from django.core.exceptions import ValidationError


class ReportCategory(models.Model):
    """
    Klasa reprezentująca kategorie zgłoszenia.

    Pola:
        name: nazwa kategorii (str)
    """
    name = models.TextField(null=False, blank=False)

    def __str__(self):
        return 'kategoria zgłoszenia: {}'.format(
            self.name,
        )

    def save(self, *args, **kwargs):
        """
        Zapisuje model kategorii zgłoszenia upewniając się że jest poprawna.
        """
        if not self.name:
            raise ValidationError(
                'Kategoria zgłoszenia nie może zostać zapisana: brak nazwy.')

        super().save(args, kwargs)


class Report(models.Model):
    """
    Klasa reprezentująca zgłoszenie.

    Pola:
        text: treść zgłoszenia (str)
        category: kategoria zgłoszenia (report.models.ReportCategory)
        user: autor zgłoszenia (common.models.User)
            lub None jeśli autor został usunięty
            lub jeśli zgłoszenie jest od niezalogowanego użytkownika
    """
    text = models.TextField(null=False, blank=False)
    category = models.ForeignKey(
        ReportCategory, on_delete=models.CASCADE, null=False, blank=False)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        if self.user:
            return 'zgłoszenie o treści "{}" dotyczace "{}" użytkownika "{}"'.format(
                self.text,
                self.category.name,
                self.user.login
            )
        else:
            return 'zgłoszenie o treści "{}" dotyczace "{}" niezalogowanego użytkownika'.format(
                self.text,
                self.category.name,
            )

    def save(self, *args, **kwargs):
        """
        Zapisuje model zgłoszenia upewniając się że jest poprawny.
        """
        if not self.text:
            raise ValidationError(
                'Zgłoszenie nie może zostać zapisane: brak treści.')

        try:
            self.category
        except(ReportCategory.DoesNotExist):
            raise ValidationError(
                'Zgłoszenie nie może zostać zapisane: brak kategorii zgłoszenia.')

        super().save(args, kwargs)

joyjoin/service/joyjoin/report/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseBadRequest

from common.context import set_common_context
from common.activity import update_activity
from report.models import Report, ReportCategory
from common.models import User


def report(request):
    """Funkcja renderująca strone report.html z podstawowymi danym na której możeym dodać opis zgłoszenia.

    Args:
        request (WSGIRequest): obiekt klasy WSGIRequest

    Returns:
        renderuje strone report.html z podstawowymi danymi
    """
    context = {}
    set_common_context(request, context)
    update_activity(context['current_user'])
    context['user_reports'] = Report.objects.filter(
        user=context['current_user']).order_by("-id")
    context['categories'] = ReportCategory.objects.all()

    # zgłoszenia do przeglądania dla admina
    # tutaj info czy zalogowany użytkownik jest adminem
    context['is_admin'] = False
    if context['is_admin']:
        context['all_reports'] = Report.objects.all().order_by("-id")

    return render(request, 'report/report.html', context)


def add(request):
    """Funkcja umożliwiająca dodanie zgłoszenia przez użytkownika.

    Args:
        request (WSGIRequest): obiekt klasy WSGIRequest

    Returns:
        przekierowuje na strone głowną po poprawnym zgłoszeniu

    Raises:
        Http404: gdy nie istnieje użytkownik.

    Note:
        Pola wykorzystywane w obiekcie request:
            - .POST['text'] (str) - treść zgłoszenia
            - .POST['category'] - kategoria zgłoszenia
    """
    try:
        text = request.POST['text']
        category = request.POST['category']
    except (KeyError):
        return HttpResponseBadRequest()

    if not text:
        return HttpResponseBadRequest()

    user_login = request.session.get('logged_in_as', default=None)
    user = None
    if user_login:
        user = get_object_or_404(User, login=user_login)

    report = Report()
    report.category = get_object_or_404(ReportCategory, name=category)
    report.text = text
    if user:
        report.user = user
    report.save()

    return redirect('all:all')

joyjoin/service/joyjoin/report/templates/report/report.html
{% extends 'common/frame.html' %}
{% load static %}

{% block sscss %}
<link href="{% static 'report/report.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block ssc %}
<div id="content" >

    <h1> Zgłoś problem </h1>

    <div id="report">
        <table>
            <tr>
                <td class="user-info">
                    {% if current_user %}
                        <a href="{% url 'user:user' current_user.login %}" class="img_login">
                        <img alt="awatar użytkownika" src="{{current_user.image_mini.url}}">
                        <i class="name">{{current_user.name}}</i>  <br>
                    {% else %}
                        <img src="{% static 'common/img/default_mini.jpg' %}" alt="user_foto">
                        <br>
                        <i class="name">Niezalogowany</i>  <br>
                    {% endif %}
                </td>
                <td>
                    <form id="report_form" action="{% url 'report:add' %}" method="post" autocomplete="off">
                        {% csrf_token %}
                        <hr class="px3">

                        Miejsce wystapienia problemu:
                        <hr class="px0">
                        <select name="category" >
                            {% for category in categories %}
                            <option value="{{category.name}}">{{category.name}}</option>
                            {% endfor %}
                        </select>

                        <hr class="px3">

                        Problem:
                        <hr class="px0">
                        <textarea  name="text" required placeholder="Napisz treść zgłoszenia..."  ></textarea>

                    </form>
                </td>
            </tr>
        </table>

        <span class="wstaw-button"><input form="report_form" type="submit" value=Wstaw></span>
        <input type="submit" class="anuluj-button" onclick="location.href='{% url 'all:all' %}';" value="Anuluj"/>

    </div>

    {% if current_user %}

        {% if user_reports %}
        <h2> Twoje zgloszenia </h2>
        {% endif %}

        {% for report in user_reports %}
            <div class="single-report">
                <table>
                    <tr>
                        <td class="user-info">
                            <a href="{% url 'user:user' current_user.login %}" class="img_login">
            				<img alt="awatar użytkownika" src="{{current_user.image_mini.url}}">
                            <br>
                            <i class="name">{{current_user.name}}</i>  <br>
                        </td>
                        <td>
                            <form method="post" autocomplete="off">
                                {% csrf_token %}
                                <hr class="px3">

                                Miejsce wystapienia problemu:
                                <hr class="px0">
                                <select disabled name="category">
                                    <option value=test>{{ report.category.name }}</option>
                                </select>

                                <hr class="px3">

                                Problem:
                                <hr class="px0">
                                <textarea disabled name="post" required placeholder="Napisz treść zgłoszenia..."  >{{ report.text }}</textarea>

                            </form>
                        </td>
                    </tr>
                </table>
            </div>
            <hr class="px3">
        {% endfor %}
    {% endif %}

    {% if is_admin %}

        {% if all_reports %}
        <h2> Wszystkie zgłoszenia </h2>
        {% endif %}

        {% for report in all_reports %}
            <div class="single-report">
                <table>
                    <tr>
                        <td class="user-info">
                            {% if report.user %}
                                <img src="{% static 'common/img/nofoto.png' %}" alt="user_foto">
                                <br>
                                <i class="name">{{ report.user.name }}</i>  <br>
                            {% else %}
                                <img src="{% static 'common/img/nofoto.png' %}" alt="user_foto">
                                <br>
                                <i class="name">Niezalogowany</i>  <br>
                            {% endif %}
                        </td>
                        <td>
                            <form method="post" autocomplete="off">
                                {% csrf_token %}
                                <hr class="px3">

                                Miejsce wystapienia problemu:
                                <hr class="px0">
                                <select disabled name="category">
                                    <option value=test>{{ report.category.name }}</option>
                                </select>

                                <hr class="px3">

                                Problem:
                                <hr class="px0">
                                <textarea disabled name="post" required placeholder="Napisz treść zgłoszenia..."  >{{ report.text }}</textarea>

                            </form>
                        </td>
                    </tr>
                </table>
            </div>
            <hr class="px3">
        {% endfor %}
    {% endif %}

</div>
{% endblock %}